[versions]
kotlin = "1.5.32"
kotest = "5.0.2"

[libraries]
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[bundles]
test = ["kotest"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
